### ISSUE TITLE
Rendering in Windows

### ISSUE THREAD

**Issue by carbonmetrics** [timelyportfolio/parcoords#14]
Works fantastic in Linux, zero issues. 
html files sent to Windows computers give mixed results. Chrome works as intended, Internet Explorer shows nothing. Firefox shows plot, axes can be moved around, but no selection is possible [I use 1D axis multi].

**Comment by timelyportfolio** [comment]
Thanks so much for the report.  I was not aware of these problems even though I use Windows.  Unfortunately, I don't have the resources to maintain the underlying `parallel-coordinates` JavaScript library, so not sure how best to handle.  Darn.

**Comment by carbonmetrics** [comment]
Darn indeed...I use this plot in markdown/html reports for (chemical) industry worldwide and it is the single most important plot for everybody once they get the hang of it. User interaction with plots is a tremendous step forward. (BTW another interesting (static) parallel coord app is Norman Matloff's freqparcoord library).

At least good to know that you don't have this problem on your machine. I will try rendering on a Windows machine if I get access to one. And thanks for all your work, really appreciate (and use!).

**Comment by timelyportfolio** [comment]
Great to hear that you are using.  I want to clarify that I do experience these same troubles.  `1d` works fine but `1d-multi` does not on Firefox, but there is no error in the console.  In IE Edge, I get console error because `__.data` is an object so there is no `forEach()` method.  I will file an issue over on the JavaScript library to see if they might be interested in working on this.

**Comment by timelyportfolio** [comment]
I think I have traced the Firefox issue to https://github.com/humanitiesplusdesign/d3.svg.multibrush/issues/2.  I'll update `d3.svg.multibrush`.  I hope it will fix at least one of the issues.

**Comment by timelyportfolio** [comment]
@carbonmetrics aec1888 should fix the problem in Firefox+Windows.  I tested on my machine, and it works.

**Comment by carbonmetrics** [comment]
Works here too. Many hanks, on behalf of many people worldwide checking their emissions data before the end of the year with this tool.

**Comment by GHDharma** [comment]
The first issue where the rendering failed due to "__.data.forEach() method" not available can be fixed in parcoords.js.
In two places the code checks for and IF condition '....constructor.name === "Object"'. In IE, the .constructor.name return "undefined" instead of "Object". Hence if we add 'typeof x.data === "object"' as an OR condition, then the parcoords renders fine.
The fixes needed are on line 119 and 193.
However, I still have issues in reordering the axis by double-clicking the axis label. The lines get reordered but the values in axis doesn't. I'll check further on that.

**Comment by timelyportfolio** [comment]
Thanks for the report.  What version of IE are you using?

**Comment by GHDharma** [comment]
Hi... I'm using IE Version 11.

Thanks
Dharma
