### ISSUE TITLE
Crosstalk: parcoords can't respond to filter_slider

### ISSUE THREAD

**Issue by tbadams45** [timelyportfolio/parcoords#27]
Based on [this block](https://bl.ocks.org/timelyportfolio/4c5718a7efe5c0abd363), it looks like parcoords/feature/crosstalk can't respond to filter events. The code below seems to corroborate this (if I'm implementing everything correctly). Is that the case currently? If so, any plans to include this feature down the road?

```
library(parcoords)
library(crosstalk)
library(htmltools)

sd <- SharedData$new(mtcars)

browsable(tagList(
  filter_slider("wt", "Weight", sd, column = ~wt, step = 0.2),
  parcoords(sd, brushMode = "1d", height = 300, width = 500)
))
```

**Comment by timelyportfolio** [comment]
Unfortunately, bidirectional with `parcoords` will be very difficult.  Programattic brushing is in the works, but even then will be very tricky to coordinate.  Don't like it, but fairly significant amount of work to just get working minimally.  For now, parcoords will serve as a controller rather than controllee.  I'll keep a close eye on the `parallel-coordinates` library to track any progress.

**Comment by tbadams45** [comment]
Understood. Thanks.

**Comment by timelyportfolio** [comment]
Just wanted to note that I have merged `crosstalk` functionality into `master`.  Going to close this for now even though not really solved.
